Repository madhaus4/spacex-stretch, pull requests merged in 2021-09, with the labels that each got.

#33 Fix/update testing
  cypress/integration/rockets_page_spec.js
Labels: testing

#35 Feature/media queries
  src/components/App/App.css
  src/components/Header/Header.css
  src/components/HistoricalCards/HistoricalCards.css
  src/components/HistoricalContainer/HistoricalContainer.css
  src/components/HomePage/HomePage.css
  src/components/RocketCards/RocketCards.css
  src/components/RocketContainer/RocketContainer.css
Labels: enhancement, feature, css

#38 Feature/error handling page
  cypress/integration/dashboard_spec.js
  cypress/integration/error_message_spec.js
  cypress/integration/rockets_page_spec.js
  public/offline.html
  src/Utils/ApiCalls.js
  src/Utils/muskQuotes.js
  src/components/App/App.js
  src/components/Error/Error.css
  src/components/Error/Error.js
  src/components/HistoricalContainer/HistoricalContainer.css
  src/components/HistoricalContainer/HistoricalContainer.js
  src/components/RocketContainer/RocketContainer.js
Labels: bug, enhancement, testing
